allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@storybook/addon-a11y@10.4.5'
  - '@storybook/addon-docs@10.4.5'
  - '@storybook/addon-onboarding@10.4.5'
  - '@storybook/addon-vitest@10.4.5'
  - '@storybook/builder-vite@10.4.5'
  - '@storybook/csf-plugin@10.4.5'
  - '@storybook/react-dom-shim@10.4.5'
  - '@storybook/react-vite@10.4.5'
  - '@storybook/react@10.4.5'
  - '@vitest/browser-playwright@4.1.9'
  - '@vitest/browser@4.1.9'
  - '@vitest/coverage-v8@4.1.9'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - eslint-plugin-storybook@10.4.5
  - playwright-core@1.61.0
  - playwright@1.61.0
  - storybook@10.4.5
  - vitest@4.1.9
